graph TD
N0["Module"]
N0 --> N1
N1["If"]
N1 --> N2
N2["ComparisonExpr"]
N2 --> N3
N3["Identifier: i"]
N2 --> N4
N4["LiteralExpr: 5"]
N1 --> N5
N5["Block"]
N5 --> N6
N6["Assign: Identifier(line=2, col=17, name='b')"]