graph TD
N0["Module"]
N0 --> N1
N1["FunctionDef: random_operation"]
N0 --> N2
N2["FunctionDef: fibonacci"]
N0 --> N3
N3["FunctionDef: fibonacci_d"]
N0 --> N4
N4["FunctionDef: iter_example"]
N0 --> N5
N5["FunctionDef: map_ex"]
N0 --> N6
N6["FunctionDef: default_ex"]
N0 --> N7
N7["FunctionDef: set_ex"]
N0 --> N8
N8["FunctionDef: tuple_ex"]
N0 --> N9
N9["FunctionDef: slices_ex"]
N0 --> N10
N10["FunctionDef: string_ex"]
N0 --> N11
N11["ExprStmt: CallExpr(line=71, col=1555, callee=Identifier(line=71, col=1550, name='print'), args=[CallExpr(line=71, col=1572, callee=Identifier(line=71, col=1556, name='random_operation'), args=[LiteralExpr(line=71, col=1573, value=5), LiteralExpr(line=71, col=1576, value=6)])])"]
N0 --> N12
N12["ExprStmt: CallExpr(line=72, col=1585, callee=Identifier(line=72, col=1580, name='print'), args=[CallExpr(line=72, col=1595, callee=Identifier(line=72, col=1586, name='fibonacci'), args=[LiteralExpr(line=72, col=1596, value=4)])])"]
N0 --> N13
N13["ExprStmt: CallExpr(line=73, col=1605, callee=Identifier(line=73, col=1600, name='print'), args=[CallExpr(line=73, col=1617, callee=Identifier(line=73, col=1606, name='fibonacci_d'), args=[LiteralExpr(line=73, col=1618, value=4)])])"]
N0 --> N14
N14["ExprStmt: CallExpr(line=74, col=1627, callee=Identifier(line=74, col=1622, name='print'), args=[CallExpr(line=74, col=1640, callee=Identifier(line=74, col=1628, name='iter_example'), args=[])])"]
N0 --> N15
N15["ExprStmt: CallExpr(line=75, col=1649, callee=Identifier(line=75, col=1644, name='print'), args=[CallExpr(line=75, col=1656, callee=Identifier(line=75, col=1650, name='map_ex'), args=[])])"]
N0 --> N16
N16["ExprStmt: CallExpr(line=76, col=1665, callee=Identifier(line=76, col=1660, name='print'), args=[CallExpr(line=76, col=1676, callee=Identifier(line=76, col=1666, name='default_ex'), args=[])])"]
N0 --> N17
N17["ExprStmt: CallExpr(line=77, col=1685, callee=Identifier(line=77, col=1680, name='print'), args=[CallExpr(line=77, col=1694, callee=Identifier(line=77, col=1686, name='tuple_ex'), args=[])])"]
N0 --> N18
N18["ExprStmt: CallExpr(line=78, col=1703, callee=Identifier(line=78, col=1698, name='print'), args=[CallExpr(line=78, col=1710, callee=Identifier(line=78, col=1704, name='set_ex'), args=[])])"]
N0 --> N19
N19["ExprStmt: CallExpr(line=79, col=1719, callee=Identifier(line=79, col=1714, name='print'), args=[CallExpr(line=79, col=1729, callee=Identifier(line=79, col=1720, name='slices_ex'), args=[])])"]
N0 --> N20
N20["ExprStmt: CallExpr(line=80, col=1742, callee=Identifier(line=80, col=1733, name='string_ex'), args=[])"]